### ISSUE TITLE
Feature Not Implemented Error on Master

### ISSUE THREAD

**Issue by shruti222patel** [PHPOffice/PHPPowerPoint#128]
I was trying out the example code: Sample_12_Reader_PowerPoint97.php when I received this exception:

[2015-07-29 05:50:38] local.ERROR: exception 'Exception' with message 'Feature not implemented (l.2044 : 0x88)' in /home/vagrant/projects/lela/vendor/phpoffice/phppowerpoint/src/PhpPowerpoint/Reader/PowerPoint97.php:2044

Stack trace:
#0 /home/vagrant/projects/lela/vendor/phpoffice/phppowerpoint/src/PhpPowerpoint/Reader/PowerPoint97.php(1360): PhpOffice\PhpPowerpoint\Reader\PowerPoint97->readRecordOfficeArtFOPT('\x0F\x00\xE8\x03\xCF\v\x00\x00\x01\x00\xE9\x03(\x00\x00...', 37268)
#1 /home/vagrant/projects/lela/vendor/phpoffice/phppowerpoint/src/PhpPowerpoint/Reader/PowerPoint97.php(1624): PhpOffice\PhpPowerpoint\Reader\PowerPoint97->readRecordOfficeArtSpContainer('\x0F\x00\xE8\x03\xCF\v\x00\x00\x01\x00\xE9\x03(\x00\x00...', 37244)
#2 /home/vagrant/projects/lela/vendor/phpoffice/phppowerpoint/src/PhpPowerpoint/Reader/PowerPoint97.php(1729): PhpOffice\PhpPowerpoint\Reader\PowerPoint97->readRecordOfficeArtSpgrContainer('\x0F\x00\xE8\x03\xCF\v\x00\x00\x01\x00\xE9\x03(\x00\x00...', 37188)
#3 /home/vagrant/projects/lela/vendor/phpoffice/phppowerpoint/src/PhpPowerpoint/Reader/PowerPoint97.php(920): PhpOffice\PhpPowerpoint\Reader\PowerPoint97->readRecordOfficeArtDgContainer('\x0F\x00\xE8\x03\xCF\v\x00\x00\x01\x00\xE9\x03(\x00\x00...', 37164)
#4 /home/vagrant/projects/lela/vendor/phpoffice/phppowerpoint/src/PhpPowerpoint/Reader/PowerPoint97.php(2583): PhpOffice\PhpPowerpoint\Reader\PowerPoint97->readRecordDrawingContainer('\x0F\x00\xE8\x03\xCF\v\x00\x00\x01\x00\xE9\x03(\x00\x00...', 37156)
#5 /home/vagrant/projects/lela/vendor/phpoffice/phppowerpoint/src/PhpPowerpoint/Reader/PowerPoint97.php(614): PhpOffice\PhpPowerpoint\Reader\PowerPoint97->readRecordSlideContainer('\x0F\x00\xE8\x03\xCF\v\x00\x00\x01\x00\xE9\x03(\x00\x00...', 37124)
#6 /home/vagrant/projects/lela/vendor/phpoffice/phppowerpoint/src/PhpPowerpoint/Reader/PowerPoint97.php(433): PhpOffice\PhpPowerpoint\Reader\PowerPoint97->loadPowerpointDocumentStream()
#7 /home/vagrant/projects/lela/vendor/phpoffice/phppowerpoint/src/PhpPowerpoint/Reader/PowerPoint97.php(412): PhpOffice\PhpPowerpoint\Reader\PowerPoint97->loadFile('/home/vagrant/p...')

Background: I'm using Laravel 5 with Homestead. Please let me know if there's any other information that I can provide to help debug this issue.

**Comment by Progi1984** [comment]
@shruti222patel Could you give us the version of PhpPowerpoint used and the file you try to read ? Thanks.

**Comment by shruti222patel** [comment]
"phpoffice/common": ">=0.1",
"phpoffice/phppowerpoint": ">=0.4",

I was trying to read in a .ppt file. Would you like me to upload it?

**Comment by Progi1984** [comment]
@shruti222patel Is seems ok for the version.

Could you upload the file on [one of these services](https://en.wikipedia.org/wiki/Category:Email_attachment_replacements), please ?

**Comment by Progi1984** [comment]
@shruti222patel PHPPowerPoint 0.6.0 has been released. I would like to solve your issue for 0.7.0. Could you answer to my question ?

**Comment by Progi1984** [comment]
@shruti222patel PhpPresentation 0.8.0 has been released. I would like to solve your issue for 0.9.0. Could you answer to my question ?

**Comment by Progi1984** [comment]
@shruti222patel PhpPresentation 0.9.0 has been released. I would like to solve your issue for 0.10.0. Could you answer to my question ?
